import { createPdfBlob } from '../frontend/src/utils/fileDownloader.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function testPdfExport() {
  const summaryFields = {
    'Document Record ID': 'REP-PORTFOLIO-01',
    'Document Category': 'Executive Operations Report',
    'Uploaded By': 'Alex Morgan (Project Director)',
    'Upload / Signoff Date': '2026-09-21',
    'Original File Size': '1.8 MB',
    'Compliance Status': 'Approved',
  };

  const reportNotes = [
    '1. High-Level Progress: Average portfolio schedule completion is tracking at target baseline velocity.',
    '2. Critical Path Tasks: 6 High/Critical priority tasks monitored across active sites.',
    '3. Inventory Health: 0 materials currently flagged for procurement reorder.',
    '4. Quality & Safety: Site hazard mitigation active; all weekly safety audits logged without critical flags.',
    '5. Budget & Cost Variance: Project draw requests align within 1.8% of committed capital forecast.',
    '6. Official Endorsement: Certified and generated by BuildOps AI Construction Intelligence Engine.',
  ];

  const blob = createPdfBlob(
    'Executive Construction Operations Report',
    'All Active Portfolio Sites',
    summaryFields,
    reportNotes,
    {
      docId: 'REP-PORTFOLIO-01',
      category: 'Executive Operations Report',
      uploadedBy: 'Alex Morgan (Project Director)',
      date: '2026-09-21',
      size: '1.8 MB',
      status: 'Approved',
    }
  );

  const arrayBuffer = await blob.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  const outPath = path.join(__dirname, 'BuildOps-Operations-Report-fixed.pdf');
  fs.writeFileSync(outPath, buffer);
  console.log(`✅ Fixed PDF written to ${outPath} (${buffer.length} bytes)`);
}

testPdfExport().catch((err) => {
  console.error('Error generating PDF:', err);
  process.exit(1);
});
